---
# SOPS encryption rules for tummycrypt
# Run scripts/sops-init.sh to generate age keys and bootstrap this config
# After init, replace AGE_PUBLIC_KEY_PLACEHOLDER with your actual public key

creation_rules:
  # Per-user S3 credentials
  - path_regex: ^credentials/seaweedfs-users/.*\.yaml$
    encrypted_regex: ^(access_key_id|secret_access_key|session_token|password)$
    age: >-
      AGE_PUBLIC_KEY_PLACEHOLDER

  # Admin/shared credentials (JWT, rclone passwords, S3 admin)
  - path_regex: ^credentials/.*\.yaml$
    encrypted_regex: ^(access_key_id|secret_access_key|jwt_signing_key|password|token|rclone_password.*)$
    age: AGE_PUBLIC_KEY_PLACEHOLDER

  # Tofu environment tfvars
  - path_regex: ^infra/tofu/environments/.*/terraform\.tfvars\.enc\.yaml$
    age: AGE_PUBLIC_KEY_PLACEHOLDER
