#!/usr/bin/env bash
# Build script for TCFS FileProvider extension.
# Compiles Swift sources, links Rust staticlib, assembles .appex bundle.
#
# Usage:
#   ./build.sh <rust_lib_dir> <rust_header_path> <output_dir> [signing_identity]
#
# Examples:
#   ./build.sh target/release include/tcfs_file_provider.h build/
#   ./build.sh target/release include/tcfs_file_provider.h build/ "Developer ID Application: ..."
#   ./build.sh target/release include/tcfs_file_provider.h build/ auto
#
# Signing identity:
#   - omitted or "-":   ad-hoc signing (development)
#   - "auto":           auto-detect Developer ID Application from Keychain
#   - other string:     use as explicit codesign identity

set -euo pipefail

RUST_LIB_DIR="${1:?Usage: build.sh <rust_lib_dir> <rust_header_path> <output_dir> [signing_identity]}"
RUST_HEADER="${2:?Usage: build.sh <rust_lib_dir> <rust_header_path> <output_dir> [signing_identity]}"
OUTPUT_DIR="${3:?Usage: build.sh <rust_lib_dir> <rust_header_path> <output_dir> [signing_identity]}"
SIGNING_IDENTITY="${4:--}"

# Auto-detect Developer ID from Keychain
if [ "$SIGNING_IDENTITY" = "auto" ]; then
  SIGNING_IDENTITY=$(security find-identity -v -p codesigning | grep "Developer ID Application" | head -1 | sed 's/.*"\(.*\)".*/\1/' || true)
  if [ -z "$SIGNING_IDENTITY" ]; then
    echo "WARNING: No Developer ID Application found in Keychain, falling back to ad-hoc" >&2
    SIGNING_IDENTITY="-"
  else
    echo "==> Auto-detected signing identity: $SIGNING_IDENTITY"
  fi
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SDKPATH="$(xcrun --sdk macosx --show-sdk-path)"
VERSION="0.1.0"
MIN_MACOS="15.0"

echo "==> Building TCFS FileProvider extension"
echo "    Rust lib:   $RUST_LIB_DIR"
echo "    Header:     $RUST_HEADER"
echo "    SDK:        $SDKPATH"
echo "    Output:     $OUTPUT_DIR"

# --- Generate embedded config ---
# Bake config.json into the extension binary at build time.
# This completely sidesteps the IPC problem: no Keychain sharing,
# no Group Container deadlocks, no restricted entitlements needed.
# The config only changes when credentials rotate, which triggers
# a home-manager rebuild anyway.
CONFIG_PATH="${TCFS_FP_CONFIG:-$HOME/.config/tcfs/fileprovider/config.json}"
mkdir -p "$OUTPUT_DIR"
EMBEDDED_CONFIG_SWIFT="$OUTPUT_DIR/EmbeddedConfig.generated.swift"

if [ -f "$CONFIG_PATH" ]; then
    CONFIG_B64=$(base64 < "$CONFIG_PATH" | tr -d '\n')
    cat > "$EMBEDDED_CONFIG_SWIFT" << SWIFT
// Auto-generated by build.sh — DO NOT EDIT
import Foundation
let embeddedConfigBase64: String? = "$CONFIG_B64"
SWIFT
    echo "==> Embedded config from $CONFIG_PATH"
else
    cat > "$EMBEDDED_CONFIG_SWIFT" << SWIFT
// Auto-generated by build.sh — DO NOT EDIT
import Foundation
let embeddedConfigBase64: String? = nil
SWIFT
    echo "WARNING: No config at $CONFIG_PATH — embedded config will be nil" >&2
    echo "         Extension will fall back to Keychain/XDG/App Group (slower, may fail)" >&2
fi

# Validate config has daemon_socket for gRPC backend
if [ -f "$CONFIG_PATH" ]; then
    if ! grep -q '"daemon_socket"' "$CONFIG_PATH" 2>/dev/null; then
        echo "WARNING: config.json has no daemon_socket — gRPC backend needs a socket path" >&2
        echo "         Extension will fall back to XDG or App Group container path" >&2
    fi
fi

# --- Compile extension binary ---
# The ObjC entry point (extension_main.m) calls NSExtensionMain() which
# handles XPC listener setup, principal class discovery, and main loop.
# Swift sources are compiled with -parse-as-library since the C entry
# point provides main().
echo "==> Compiling FileProvider extension..."

# Generate combined bridging header (cbindgen + supplementary progress callback)
cat > "$OUTPUT_DIR/tcfs_combined_bridge.h" << BRIDGE
/* Combined bridging header for Swift — auto-generated by build.sh */
#include <stdint.h>
$(cat "$RUST_HEADER")

/* Supplementary: progress callback (cbindgen doesn't export complex fn ptr types) */
typedef void (*TcfsProgressCallback)(uint64_t completed, uint64_t total, const void *context);

enum TcfsError tcfs_provider_fetch_with_progress(
    struct TcfsProvider *provider,
    const char *item_id,
    const char *dest_path,
    TcfsProgressCallback callback,
    const void *callback_context
);
BRIDGE

# Compile ObjC entry point
/usr/bin/clang -c \
    -isysroot "$SDKPATH" \
    -target arm64-apple-macos${MIN_MACOS} \
    -fobjc-arc \
    -O2 \
    -o extension_main.o \
    "$SCRIPT_DIR/Sources/Extension/extension_main.m"

# Compile Swift sources + link everything
# -disable-modules-validate-system-headers: work around CLT packaging bug where
# the compiler version (e.g. Swift 6.2.4) is newer than the SDK's pre-built
# Swift module interfaces (e.g. Swift 6.2). Safe for production builds.
/usr/bin/swiftc \
    -sdk "$SDKPATH" \
    -parse-as-library \
    -framework FileProvider \
    -framework Foundation \
    -target arm64-apple-macos${MIN_MACOS} \
    -import-objc-header "$OUTPUT_DIR/tcfs_combined_bridge.h" \
    -Xfrontend -disable-modules-validate-system-headers \
    -Xlinker -all_load \
    -L "$RUST_LIB_DIR" -ltcfs_file_provider \
    -lc++ \
    -O \
    -o TCFSFileProvider \
    "$SCRIPT_DIR/Sources/Extension/"*.swift \
    "$EMBEDDED_CONFIG_SWIFT" \
    extension_main.o

# --- Compile host app binary ---
echo "==> Compiling host app..."
/usr/bin/swiftc \
    -sdk "$SDKPATH" \
    -parse-as-library \
    -framework FileProvider \
    -framework Foundation \
    -target arm64-apple-macos${MIN_MACOS} \
    -Xfrontend -disable-modules-validate-system-headers \
    -O \
    -o TCFSProvider \
    "$SCRIPT_DIR/Sources/HostApp/"*.swift

# --- Compile Finder Sync extension (status badges) ---
FINDER_SYNC_DIR="$SCRIPT_DIR/Sources/FinderSync"
if [ -d "$FINDER_SYNC_DIR" ]; then
    echo "==> Compiling Finder Sync extension..."

    # FinderSync is an AppKit-based in-process plugin (NOT an XPC service).
    # Uses NSApplicationMain entry point (NOT NSExtensionMain).
    /usr/bin/clang -c \
        -isysroot "$SDKPATH" \
        -target arm64-apple-macos${MIN_MACOS} \
        -fobjc-arc \
        -O2 \
        -o finder_sync_main.o \
        "$FINDER_SYNC_DIR/finder_sync_main.m"

    /usr/bin/swiftc \
        -sdk "$SDKPATH" \
        -parse-as-library \
        -framework FinderSync \
        -framework Foundation \
        -framework AppKit \
        -target arm64-apple-macos${MIN_MACOS} \
        -Xfrontend -disable-modules-validate-system-headers \
        -O \
        -o TCFSFinderSync \
        "$FINDER_SYNC_DIR/"*.swift \
        finder_sync_main.o
    HAVE_FINDER_SYNC=true
else
    echo "==> No FinderSync sources found, skipping"
    HAVE_FINDER_SYNC=false
fi

# --- Assemble bundle ---
echo "==> Assembling bundle..."
APP="$OUTPUT_DIR/TCFSProvider.app/Contents"
EXT="$APP/Extensions/TCFSFileProvider.appex/Contents"

mkdir -p "$APP/MacOS" "$EXT/MacOS"

cp TCFSProvider "$APP/MacOS/"
cp "$SCRIPT_DIR/resources/HostApp-Info.plist" "$APP/Info.plist"

cp TCFSFileProvider "$EXT/MacOS/"
cp "$SCRIPT_DIR/resources/Extension-Info.plist" "$EXT/Info.plist"

# Finder Sync extension (if compiled)
if [ "$HAVE_FINDER_SYNC" = "true" ]; then
    FSEXT="$APP/Extensions/TCFSFinderSync.appex/Contents"
    mkdir -p "$FSEXT/MacOS"
    cp TCFSFinderSync "$FSEXT/MacOS/"
    cp "$SCRIPT_DIR/resources/FinderSync-Info.plist" "$FSEXT/Info.plist"
fi

# --- Resolve entitlements (expand TeamID for keychain-access-groups) ---
echo "==> Resolving entitlements..."
EXT_ENTITLEMENTS="$SCRIPT_DIR/resources/Extension.entitlements"
HOST_ENTITLEMENTS="$SCRIPT_DIR/resources/HostApp.entitlements"

if [ "$SIGNING_IDENTITY" != "-" ]; then
    # Extract TeamID from the signing certificate.
    TEAM_ID=$(/usr/bin/security find-identity -v -p codesigning \
        | grep "$SIGNING_IDENTITY" \
        | head -1 \
        | sed -E 's/.*\(([A-Z0-9]{10})\).*/\1/')
    if [ -n "$TEAM_ID" ]; then
        echo "    TeamID: $TEAM_ID"
        # Generate entitlements with resolved keychain-access-groups
        EXT_ENTITLEMENTS="/tmp/tcfs-ext-entitlements.$$.plist"
        HOST_ENTITLEMENTS="/tmp/tcfs-host-entitlements.$$.plist"
        sed "s/\$(AppIdentifierPrefix)/${TEAM_ID}./g" \
            "$SCRIPT_DIR/resources/Extension.entitlements" > "$EXT_ENTITLEMENTS"
        sed "s/\$(AppIdentifierPrefix)/${TEAM_ID}./g" \
            "$SCRIPT_DIR/resources/HostApp.entitlements" > "$HOST_ENTITLEMENTS"
    else
        echo "    WARNING: Could not extract TeamID, using entitlements as-is"
    fi
fi

# --- Code sign (inside-out: extensions first, then host app) ---
echo "==> Signing..."
FINDER_SYNC_ENTITLEMENTS="$SCRIPT_DIR/resources/FinderSync.entitlements"

if [ "$SIGNING_IDENTITY" != "-" ]; then
    echo "    Identity: $SIGNING_IDENTITY (Developer ID)"
    /usr/bin/codesign -f -s "$SIGNING_IDENTITY" \
        --options runtime --timestamp \
        --entitlements "$EXT_ENTITLEMENTS" \
        "$APP/Extensions/TCFSFileProvider.appex"

    if [ "$HAVE_FINDER_SYNC" = "true" ]; then
        /usr/bin/codesign -f -s "$SIGNING_IDENTITY" \
            --options runtime --timestamp \
            --entitlements "$FINDER_SYNC_ENTITLEMENTS" \
            "$APP/Extensions/TCFSFinderSync.appex"
    fi

    /usr/bin/codesign -f -s "$SIGNING_IDENTITY" \
        --options runtime --timestamp \
        --entitlements "$HOST_ENTITLEMENTS" \
        "$OUTPUT_DIR/TCFSProvider.app"
else
    echo "    Identity: ad-hoc (development)"
    /usr/bin/codesign -f -s - \
        --entitlements "$EXT_ENTITLEMENTS" \
        "$APP/Extensions/TCFSFileProvider.appex"

    if [ "$HAVE_FINDER_SYNC" = "true" ]; then
        /usr/bin/codesign -f -s - \
            --entitlements "$FINDER_SYNC_ENTITLEMENTS" \
            "$APP/Extensions/TCFSFinderSync.appex"
    fi

    /usr/bin/codesign -f -s - \
        --entitlements "$HOST_ENTITLEMENTS" \
        "$OUTPUT_DIR/TCFSProvider.app"
fi

# --- Validate outputs ---
echo "==> Validating..."
if [ ! -f "$APP/MacOS/TCFSProvider" ]; then
    echo "ERROR: host app binary missing: $APP/MacOS/TCFSProvider" >&2
    exit 1
fi
if [ ! -f "$EXT/MacOS/TCFSFileProvider" ]; then
    echo "ERROR: extension binary missing: $EXT/MacOS/TCFSFileProvider" >&2
    exit 1
fi
/usr/bin/codesign -v "$OUTPUT_DIR/TCFSProvider.app" 2>/dev/null || {
    echo "ERROR: code signature validation failed for TCFSProvider.app" >&2
    exit 1
}
/usr/bin/codesign -v "$APP/Extensions/TCFSFileProvider.appex" 2>/dev/null || {
    echo "ERROR: code signature validation failed for TCFSFileProvider.appex" >&2
    exit 1
}
echo "    Host app:  OK"
echo "    Extension: OK"

# --- Cleanup temp binaries ---
rm -f TCFSFileProvider TCFSProvider TCFSFinderSync extension_main.o finder_sync_main.o
rm -f "$EMBEDDED_CONFIG_SWIFT"

echo "==> Done: $OUTPUT_DIR/TCFSProvider.app"
