[daemon]
socket = "/tmp/nix-shell.LpfJD1/tcfs-lazy-linux-demo.GZnPLW/no-daemon.sock"

[storage]
endpoint = "http://100.64.48.53:8333"
region = "us-east-1"
bucket = "tcfs"
remote_prefix = "lazy-linux-20260508T170825Z"
enforce_tls = false

[sync]
state_db = "/tmp/nix-shell.LpfJD1/tcfs-lazy-linux-demo.GZnPLW/state.db"
sync_root = "/tmp/nix-shell.LpfJD1/tcfs-lazy-linux-demo.GZnPLW/source"
nats_url = "nats://localhost:4222"
nats_tls = false
sync_empty_dirs = true

[fuse]
cache_dir = "/tmp/nix-shell.LpfJD1/tcfs-lazy-linux-demo.GZnPLW/cache"
cache_max_mb = 64
negative_cache_ttl_secs = 1

[crypto]
enabled = false
