//! Device enrollment protocol — invite-based onboarding for new devices.
//!
//! # Flow
//!
//! 1. Admin device generates an `EnrollmentInvite` (QR code or deep link)
//! 2. New device scans QR / opens link → submits `EnrollmentRequest`
//! 3. Admin approves (auto-approve if invite hasn't expired)
//! 4. New device receives `EnrollmentResult` with device ID + credentials
//! 5. New device registers auth credential (TOTP secret, WebAuthn key, etc.)
//!
//! # Security Model
//!
//! - Invites are signed with the admin device's key (BLAKE3-HMAC)
//! - The signature covers the full invite payload except the signature itself
//! - Each invite has a single-use nonce and expiry
//! - Invite can be scoped to specific permissions
//! - Revocation is immediate (admin removes device from registry)

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use thiserror::Error;
use tokio::sync::RwLock;

use crate::session::DevicePermissions;

/// An enrollment invite generated by an admin device.
///
/// Encode as JSON → base64 → QR code or `tcfs://enroll?data=...` deep link.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnrollmentInvite {
    /// Unique invite ID (UUID v4).
    pub invite_id: String,
    /// Single-use nonce (random 16 bytes, hex-encoded).
    pub nonce: String,
    /// Admin device ID that created the invite.
    pub created_by: String,
    /// Invite creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Invite expiry timestamp.
    pub expires_at: DateTime<Utc>,
    /// Permissions granted to the enrolled device.
    pub permissions: DevicePermissions,
    /// BLAKE3-HMAC signature of the invite payload (signed by admin's master key).
    pub signature: String,
    /// Optional: NATS server URL for the fleet.
    pub nats_url: Option<String>,
    /// Optional: S3/SeaweedFS endpoint for storage.
    pub storage_endpoint: Option<String>,
    /// Optional: S3 bucket name.
    pub storage_bucket: Option<String>,
    /// Optional: S3 access key (credential brokering).
    pub storage_access_key: Option<String>,
    /// Optional: S3 secret key (credential brokering).
    pub storage_secret_key: Option<String>,
    /// Optional: remote prefix for file sync.
    pub remote_prefix: Option<String>,
    /// Optional: encryption passphrase for E2EE.
    pub encryption_passphrase: Option<String>,
    /// Optional: encryption salt for KDF.
    pub encryption_salt: Option<String>,
    /// Optional: human-readable description of the invite.
    pub description: Option<String>,
}

impl EnrollmentInvite {
    /// Create a new enrollment invite.
    ///
    /// `admin_device_id`: the device creating the invite.
    /// `master_key`: 32-byte master key for HMAC signing.
    /// `ttl_hours`: how long the invite is valid.
    pub fn new(
        admin_device_id: &str,
        master_key: &[u8; 32],
        ttl_hours: u64,
        permissions: DevicePermissions,
    ) -> Self {
        let invite_id = uuid::Uuid::new_v4().to_string();
        let mut nonce_bytes = [0u8; 16];
        rand::RngCore::fill_bytes(&mut rand::rngs::OsRng, &mut nonce_bytes);
        let nonce = hex::encode(nonce_bytes);
        let now = Utc::now();
        let expires_at = now + chrono::Duration::hours(ttl_hours as i64);

        let mut invite = Self {
            invite_id,
            nonce,
            created_by: admin_device_id.to_string(),
            created_at: now,
            expires_at,
            permissions,
            signature: String::new(),
            nats_url: None,
            storage_endpoint: None,
            storage_bucket: None,
            storage_access_key: None,
            storage_secret_key: None,
            remote_prefix: None,
            encryption_passphrase: None,
            encryption_salt: None,
            description: None,
        };

        invite.signature = invite.compute_signature(master_key);
        invite
    }

    /// Recompute the invite signature after mutating optional payload fields.
    pub fn refresh_signature(&mut self, master_key: &[u8; 32]) {
        self.signature = self.compute_signature(master_key);
    }

    /// Compute BLAKE3-keyed-MAC of the invite payload.
    fn compute_signature(&self, master_key: &[u8; 32]) -> String {
        let payload = serde_json::to_vec(&InviteSignaturePayload::from_invite(self))
            .expect("serialize invite signature payload");
        let mac = blake3::keyed_hash(master_key, &payload);
        mac.to_hex().to_string()
    }

    /// Verify the invite signature against a master key.
    ///
    /// Uses constant-time comparison to prevent timing side-channel attacks.
    pub fn verify_signature(&self, master_key: &[u8; 32]) -> bool {
        let expected = self.compute_signature(master_key);
        constant_time_eq(expected.as_bytes(), self.signature.as_bytes())
    }

    /// Check if the invite has expired.
    pub fn is_expired(&self) -> bool {
        Utc::now() > self.expires_at
    }

    /// Check if the invite is valid (not expired and signature matches).
    pub fn is_valid(&self, master_key: &[u8; 32]) -> bool {
        !self.is_expired() && self.verify_signature(master_key)
    }

    /// Encode the invite as a base64 JSON string (for QR code / deep link).
    pub fn encode(&self) -> anyhow::Result<String> {
        let json = serde_json::to_vec(self)?;
        Ok(base64::Engine::encode(
            &base64::engine::general_purpose::URL_SAFE_NO_PAD,
            &json,
        ))
    }

    /// Decode an invite from a base64 JSON string.
    pub fn decode(encoded: &str) -> anyhow::Result<Self> {
        let json =
            base64::Engine::decode(&base64::engine::general_purpose::URL_SAFE_NO_PAD, encoded)?;
        Ok(serde_json::from_slice(&json)?)
    }

    /// Generate a `tcfs://enroll?data=...` deep link URI.
    pub fn to_deep_link(&self) -> anyhow::Result<String> {
        Ok(format!("tcfs://enroll?data={}", self.encode()?))
    }

    /// Encode as a compact representation for QR codes.
    ///
    /// Uses short JSON keys, omits null fields, and applies zstd compression.
    /// Typically produces ~200-300 bytes encoded vs ~1200 for the full format.
    pub fn encode_compact(&self) -> anyhow::Result<String> {
        let compact = CompactInvite::from_full(self);
        let json = serde_json::to_vec(&compact)?;
        // zstd compress at level 3 (fast, good ratio for small payloads)
        let compressed = zstd::encode_all(json.as_slice(), 3)
            .map_err(|e| anyhow::anyhow!("zstd compress failed: {e}"))?;
        Ok(base64::Engine::encode(
            &base64::engine::general_purpose::URL_SAFE_NO_PAD,
            &compressed,
        ))
    }

    /// Decode from compact representation.
    pub fn decode_compact(encoded: &str) -> anyhow::Result<Self> {
        let compressed =
            base64::Engine::decode(&base64::engine::general_purpose::URL_SAFE_NO_PAD, encoded)?;
        let json = zstd::decode_all(compressed.as_slice())
            .map_err(|e| anyhow::anyhow!("zstd decompress failed: {e}"))?;
        let compact: CompactInvite = serde_json::from_slice(&json)?;
        Ok(compact.to_full())
    }

    /// Decode from either compact or full format (auto-detect).
    ///
    /// Compact payloads start with a zstd magic number (0x28B52FFD) after
    /// base64 decoding. Full payloads start with `{` (0x7B) as JSON.
    pub fn decode_any(encoded: &str) -> anyhow::Result<Self> {
        let raw =
            base64::Engine::decode(&base64::engine::general_purpose::URL_SAFE_NO_PAD, encoded)?;
        // zstd magic: 0xFD2FB528 (little-endian: 28 B5 2F FD)
        if raw.len() >= 4 && raw[0] == 0x28 && raw[1] == 0xB5 && raw[2] == 0x2F && raw[3] == 0xFD {
            let json = zstd::decode_all(raw.as_slice())
                .map_err(|e| anyhow::anyhow!("zstd decompress failed: {e}"))?;
            let compact: CompactInvite = serde_json::from_slice(&json)?;
            Ok(compact.to_full())
        } else {
            Ok(serde_json::from_slice(&raw)?)
        }
    }

    /// Generate a compact `tcfs://enroll?data=...` deep link URI.
    pub fn to_compact_deep_link(&self) -> anyhow::Result<String> {
        Ok(format!("tcfs://enroll?data={}", self.encode_compact()?))
    }
}

#[derive(Serialize)]
struct InviteSignaturePayload<'a> {
    invite_id: &'a str,
    nonce: &'a str,
    created_by: &'a str,
    created_at: i64,
    expires_at: i64,
    permissions: &'a DevicePermissions,
    nats_url: Option<&'a str>,
    storage_endpoint: Option<&'a str>,
    storage_bucket: Option<&'a str>,
    storage_access_key: Option<&'a str>,
    storage_secret_key: Option<&'a str>,
    remote_prefix: Option<&'a str>,
    encryption_passphrase: Option<&'a str>,
    encryption_salt: Option<&'a str>,
    description: Option<&'a str>,
}

impl<'a> InviteSignaturePayload<'a> {
    fn from_invite(invite: &'a EnrollmentInvite) -> Self {
        Self {
            invite_id: &invite.invite_id,
            nonce: &invite.nonce,
            created_by: &invite.created_by,
            created_at: invite.created_at.timestamp(),
            expires_at: invite.expires_at.timestamp(),
            permissions: &invite.permissions,
            nats_url: invite.nats_url.as_deref(),
            storage_endpoint: invite.storage_endpoint.as_deref(),
            storage_bucket: invite.storage_bucket.as_deref(),
            storage_access_key: invite.storage_access_key.as_deref(),
            storage_secret_key: invite.storage_secret_key.as_deref(),
            remote_prefix: invite.remote_prefix.as_deref(),
            encryption_passphrase: invite.encryption_passphrase.as_deref(),
            encryption_salt: invite.encryption_salt.as_deref(),
            description: invite.description.as_deref(),
        }
    }
}

/// Compact invite representation with short keys for QR-friendly encoding.
///
/// Field mapping:
/// - `i` = invite_id, `n` = nonce, `b` = created_by
/// - `c` = created_at (unix ts), `x` = expires_at (unix ts)
/// - `p` = permissions (bitfield: mount=1, push=2, pull=4, admin=8)
/// - `g` = signature
/// - `u` = nats_url, `e` = storage_endpoint, `k` = storage_bucket
/// - `a` = storage_access_key, `s` = storage_secret_key
/// - `r` = remote_prefix, `w` = encryption_passphrase
/// - `t` = encryption_salt, `d` = description
#[derive(Debug, Clone, Serialize, Deserialize)]
struct CompactInvite {
    i: String,
    n: String,
    b: String,
    c: i64,
    x: i64,
    p: u8,
    g: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    u: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    e: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    k: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    a: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    s: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    r: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    w: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    t: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    d: Option<String>,
}

impl CompactInvite {
    fn from_full(inv: &EnrollmentInvite) -> Self {
        let perms = (inv.permissions.can_mount as u8)
            | ((inv.permissions.can_push as u8) << 1)
            | ((inv.permissions.can_pull as u8) << 2)
            | ((inv.permissions.can_admin as u8) << 3);
        Self {
            i: inv.invite_id.clone(),
            n: inv.nonce.clone(),
            b: inv.created_by.clone(),
            c: inv.created_at.timestamp(),
            x: inv.expires_at.timestamp(),
            p: perms,
            g: inv.signature.clone(),
            u: inv.nats_url.clone(),
            e: inv.storage_endpoint.clone(),
            k: inv.storage_bucket.clone(),
            a: inv.storage_access_key.clone(),
            s: inv.storage_secret_key.clone(),
            r: inv.remote_prefix.clone(),
            w: inv.encryption_passphrase.clone(),
            t: inv.encryption_salt.clone(),
            d: inv.description.clone(),
        }
    }

    fn to_full(&self) -> EnrollmentInvite {
        EnrollmentInvite {
            invite_id: self.i.clone(),
            nonce: self.n.clone(),
            created_by: self.b.clone(),
            created_at: chrono::DateTime::from_timestamp(self.c, 0).unwrap_or_else(Utc::now),
            expires_at: chrono::DateTime::from_timestamp(self.x, 0).unwrap_or_else(Utc::now),
            permissions: DevicePermissions {
                can_mount: self.p & 1 != 0,
                can_push: self.p & 2 != 0,
                can_pull: self.p & 4 != 0,
                can_admin: self.p & 8 != 0,
                allowed_prefixes: vec![],
            },
            signature: self.g.clone(),
            nats_url: self.u.clone(),
            storage_endpoint: self.e.clone(),
            storage_bucket: self.k.clone(),
            storage_access_key: self.a.clone(),
            storage_secret_key: self.s.clone(),
            remote_prefix: self.r.clone(),
            encryption_passphrase: self.w.clone(),
            encryption_salt: self.t.clone(),
            description: self.d.clone(),
        }
    }
}

/// A request from a new device to enroll using an invite.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnrollmentRequest {
    /// The invite being redeemed.
    pub invite_id: String,
    /// Invite nonce (proves possession of the invite).
    pub nonce: String,
    /// Requested device name.
    pub device_name: String,
    /// Device's public key (age X25519).
    pub public_key: String,
    /// Device platform (e.g., "macos-aarch64", "ios", "linux-x86_64").
    pub platform: String,
}

/// Result of a successful enrollment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnrollmentResult {
    /// Assigned device ID (UUID v4).
    pub device_id: String,
    /// Assigned device name (may differ from requested).
    pub device_name: String,
    /// Device permissions.
    pub permissions: DevicePermissions,
    /// NATS server URL (if fleet sync is enabled).
    pub nats_url: Option<String>,
    /// Storage endpoint URL.
    pub storage_endpoint: Option<String>,
    /// S3 bucket name.
    pub storage_bucket: Option<String>,
    /// S3 access key (brokered from invite).
    pub storage_access_key: Option<String>,
    /// S3 secret key (brokered from invite).
    pub storage_secret_key: Option<String>,
    /// Remote prefix for file sync.
    pub remote_prefix: Option<String>,
    /// Encryption passphrase (if E2EE enabled).
    pub encryption_passphrase: Option<String>,
    /// Encryption salt (if E2EE enabled).
    pub encryption_salt: Option<String>,
    /// Auth methods available (e.g., ["totp", "webauthn"]).
    pub available_auth_methods: Vec<String>,
}

/// Secret bootstrap material returned to a joining device.
///
/// This payload must be encrypted to the joining device's public key before it
/// crosses an enrollment boundary.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct EnrollmentBootstrap {
    /// NATS server URL (if fleet sync is enabled).
    pub nats_url: Option<String>,
    /// Storage endpoint URL.
    pub storage_endpoint: Option<String>,
    /// S3 bucket name.
    pub storage_bucket: Option<String>,
    /// S3 access key.
    pub storage_access_key: Option<String>,
    /// S3 secret key.
    pub storage_secret_key: Option<String>,
    /// Remote prefix for file sync.
    pub remote_prefix: Option<String>,
    /// Base64-encoded TCFS master key for the current shared-master fleet.
    pub master_key_base64: Option<String>,
    /// Encryption salt (if passphrase-based E2EE is enabled).
    pub encryption_salt: Option<String>,
}

/// Audit record for an invite that has already been redeemed.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InviteRedemption {
    /// Redeemed invite ID.
    pub invite_id: String,
    /// Redeemed invite nonce.
    pub nonce: String,
    /// UTC timestamp when the daemon accepted the redemption.
    pub redeemed_at: DateTime<Utc>,
    /// Device name requested during redemption.
    pub device_name: String,
    /// Device public key presented during redemption.
    pub public_key: String,
    /// Device platform presented during redemption.
    pub platform: String,
}

#[derive(Debug, Error)]
pub enum InviteRedemptionError {
    #[error("invite {invite_id} has already been redeemed")]
    AlreadyRedeemed { invite_id: String },
}

/// Thread-safe single-use invite redemption ledger.
///
/// The key is `(invite_id, nonce)` so a malicious client cannot replay an
/// otherwise valid invite payload after the first successful enrollment.
#[derive(Clone, Default)]
pub struct InviteRedemptionStore {
    redemptions: Arc<RwLock<HashMap<String, InviteRedemption>>>,
}

impl InviteRedemptionStore {
    pub fn new() -> Self {
        Self::default()
    }

    fn key(invite_id: &str, nonce: &str) -> String {
        format!("{invite_id}:{nonce}")
    }

    /// Claim an invite nonce. Returns an error if it has already been used.
    pub async fn claim(
        &self,
        invite_id: &str,
        nonce: &str,
        device_name: &str,
        public_key: &str,
        platform: &str,
    ) -> Result<InviteRedemption, InviteRedemptionError> {
        let key = Self::key(invite_id, nonce);
        let mut redemptions = self.redemptions.write().await;
        if redemptions.contains_key(&key) {
            return Err(InviteRedemptionError::AlreadyRedeemed {
                invite_id: invite_id.to_string(),
            });
        }

        let redemption = InviteRedemption {
            invite_id: invite_id.to_string(),
            nonce: nonce.to_string(),
            redeemed_at: Utc::now(),
            device_name: device_name.to_string(),
            public_key: public_key.to_string(),
            platform: platform.to_string(),
        };
        redemptions.insert(key, redemption.clone());
        Ok(redemption)
    }

    pub async fn is_redeemed(&self, invite_id: &str, nonce: &str) -> bool {
        self.redemptions
            .read()
            .await
            .contains_key(&Self::key(invite_id, nonce))
    }

    pub async fn count(&self) -> usize {
        self.redemptions.read().await.len()
    }

    pub async fn save_to_file(&self, path: &std::path::Path) -> anyhow::Result<()> {
        let redemptions = self.redemptions.read().await;
        let data = serde_json::to_string_pretty(&*redemptions)?;
        if let Some(parent) = path.parent() {
            tokio::fs::create_dir_all(parent).await?;
        }
        tokio::fs::write(path, data).await?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))?;
        }
        Ok(())
    }

    pub async fn load_from_file(&self, path: &std::path::Path) -> anyhow::Result<()> {
        let data = tokio::fs::read_to_string(path).await?;
        let loaded: HashMap<String, InviteRedemption> = serde_json::from_str(&data)?;
        let mut redemptions = self.redemptions.write().await;
        redemptions.clear();
        redemptions.extend(loaded);
        Ok(())
    }
}

// Need hex for nonce encoding
mod hex {
    pub fn encode(bytes: impl AsRef<[u8]>) -> String {
        bytes.as_ref().iter().map(|b| format!("{b:02x}")).collect()
    }
}

/// Constant-time byte comparison to prevent timing side-channel attacks.
/// Compares all bytes regardless of early mismatches.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_invite_create_and_verify() {
        let master_key = [42u8; 32];
        let invite = EnrollmentInvite::new(
            "admin-device",
            &master_key,
            24,
            DevicePermissions::default(),
        );

        assert!(!invite.is_expired());
        assert!(invite.verify_signature(&master_key));
        assert!(invite.is_valid(&master_key));

        // Wrong key should fail
        let wrong_key = [0u8; 32];
        assert!(!invite.verify_signature(&wrong_key));
    }

    #[test]
    fn test_invite_encode_decode_roundtrip() {
        let master_key = [42u8; 32];
        let invite =
            EnrollmentInvite::new("admin-device", &master_key, 24, DevicePermissions::admin());

        let encoded = invite.encode().unwrap();
        let decoded = EnrollmentInvite::decode(&encoded).unwrap();

        assert_eq!(invite.invite_id, decoded.invite_id);
        assert_eq!(invite.nonce, decoded.nonce);
        assert_eq!(invite.created_by, decoded.created_by);
        assert_eq!(invite.signature, decoded.signature);
        assert!(decoded.verify_signature(&master_key));
    }

    #[test]
    fn test_deep_link() {
        let master_key = [42u8; 32];
        let invite = EnrollmentInvite::new(
            "admin-device",
            &master_key,
            1,
            DevicePermissions::read_only(),
        );

        let link = invite.to_deep_link().unwrap();
        assert!(link.starts_with("tcfs://enroll?data="));

        // Extract data param and decode
        let data = link.strip_prefix("tcfs://enroll?data=").unwrap();
        let decoded = EnrollmentInvite::decode(data).unwrap();
        assert_eq!(invite.invite_id, decoded.invite_id);
    }

    #[test]
    fn test_compact_encode_decode_roundtrip() {
        let master_key = [42u8; 32];
        let mut invite =
            EnrollmentInvite::new("admin-device", &master_key, 24, DevicePermissions::admin());
        invite.storage_endpoint = Some("http://s3.example.com:8333".into());
        invite.storage_bucket = Some("tcfs".into());
        invite.storage_access_key = Some("AKIAIOSFODNN7EXAMPLE".into());
        invite.storage_secret_key = Some("wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY".into());
        invite.remote_prefix = Some("default".into());
        invite.nats_url = Some("nats://nats.example.com:4222".into());
        invite.description = Some("test invite".into());
        invite.refresh_signature(&master_key);

        let compact = invite.encode_compact().unwrap();
        let full = invite.encode().unwrap();

        // Compact should be significantly smaller
        assert!(
            compact.len() < full.len(),
            "compact ({}) should be smaller than full ({})",
            compact.len(),
            full.len()
        );

        // Roundtrip via decode_compact
        let decoded = EnrollmentInvite::decode_compact(&compact).unwrap();
        assert_eq!(invite.invite_id, decoded.invite_id);
        assert_eq!(invite.storage_endpoint, decoded.storage_endpoint);
        assert_eq!(invite.storage_access_key, decoded.storage_access_key);
        assert_eq!(invite.nats_url, decoded.nats_url);
        assert_eq!(invite.description, decoded.description);
        assert!(decoded.verify_signature(&master_key));

        // Roundtrip via decode_any (auto-detect compact)
        let decoded2 = EnrollmentInvite::decode_any(&compact).unwrap();
        assert_eq!(invite.invite_id, decoded2.invite_id);

        // decode_any also handles full format
        let decoded3 = EnrollmentInvite::decode_any(&full).unwrap();
        assert_eq!(invite.invite_id, decoded3.invite_id);
    }

    #[test]
    fn test_compact_deep_link() {
        let master_key = [42u8; 32];
        let mut invite = EnrollmentInvite::new(
            "admin-device",
            &master_key,
            1,
            DevicePermissions::read_only(),
        );
        invite.storage_endpoint = Some("http://212.2.245.145:8333".into());
        invite.storage_bucket = Some("tcfs".into());
        invite.storage_access_key = Some("TESTKEY123".into());
        invite.storage_secret_key = Some("TESTSECRET456".into());
        invite.refresh_signature(&master_key);

        let link = invite.to_compact_deep_link().unwrap();
        assert!(link.starts_with("tcfs://enroll?data="));

        let data = link.strip_prefix("tcfs://enroll?data=").unwrap();
        // Should be decodable via decode_any
        let decoded = EnrollmentInvite::decode_any(data).unwrap();
        assert_eq!(invite.invite_id, decoded.invite_id);
        assert_eq!(invite.storage_endpoint, decoded.storage_endpoint);

        // Payload should be small enough for QR (~500 chars max for reliable scanning)
        assert!(
            data.len() < 500,
            "compact payload {} bytes, should be under 500 for QR",
            data.len()
        );
    }

    #[test]
    fn test_signature_covers_brokered_payload_fields() {
        let master_key = [42u8; 32];
        let mut invite =
            EnrollmentInvite::new("admin-device", &master_key, 24, DevicePermissions::admin());
        invite.storage_endpoint = Some("https://s3.example.com".into());
        invite.storage_bucket = Some("tcfs".into());
        invite.storage_access_key = Some("AKIAIOSFODNN7EXAMPLE".into());
        invite.storage_secret_key = Some("secret-before".into());
        invite.remote_prefix = Some("tenant/a".into());
        invite.encryption_passphrase = Some("passphrase-before".into());
        invite.refresh_signature(&master_key);

        assert!(invite.verify_signature(&master_key));

        let mut tampered_secret = invite.clone();
        tampered_secret.storage_secret_key = Some("secret-after".into());
        assert!(!tampered_secret.verify_signature(&master_key));

        let mut tampered_prefix = invite.clone();
        tampered_prefix.remote_prefix = Some("tenant/b".into());
        assert!(!tampered_prefix.verify_signature(&master_key));

        let mut tampered_permissions = invite.clone();
        tampered_permissions.permissions.can_admin = false;
        assert!(!tampered_permissions.verify_signature(&master_key));
    }

    #[tokio::test]
    async fn test_invite_redemption_store_rejects_reuse() {
        let master_key = [42u8; 32];
        let invite = EnrollmentInvite::new(
            "admin-device",
            &master_key,
            24,
            DevicePermissions::default(),
        );
        let store = InviteRedemptionStore::new();

        let first = store
            .claim(
                &invite.invite_id,
                &invite.nonce,
                "laptop",
                "age1test",
                "linux-x86_64",
            )
            .await;
        assert!(first.is_ok());
        assert!(store.is_redeemed(&invite.invite_id, &invite.nonce).await);

        let second = store
            .claim(
                &invite.invite_id,
                &invite.nonce,
                "tablet",
                "age1other",
                "ios",
            )
            .await;
        assert!(matches!(
            second,
            Err(InviteRedemptionError::AlreadyRedeemed { .. })
        ));
        assert_eq!(store.count().await, 1);
    }

    #[tokio::test]
    async fn test_invite_redemption_store_save_load_roundtrip() {
        let master_key = [42u8; 32];
        let invite = EnrollmentInvite::new(
            "admin-device",
            &master_key,
            24,
            DevicePermissions::default(),
        );
        let store = InviteRedemptionStore::new();
        store
            .claim(
                &invite.invite_id,
                &invite.nonce,
                "laptop",
                "age1test",
                "linux-x86_64",
            )
            .await
            .unwrap();

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("invite-redemptions.json");
        store.save_to_file(&path).await.unwrap();

        let loaded = InviteRedemptionStore::new();
        loaded.load_from_file(&path).await.unwrap();
        assert!(loaded.is_redeemed(&invite.invite_id, &invite.nonce).await);
        assert_eq!(loaded.count().await, 1);
    }
}
