//! Centralized exclusion logic for the sync pipeline.
//!
//! Consolidates six scattered filtering sites (watcher, engine, VFS, git safety)
//! into a single `Blacklist` type with a unified `check()` method.

use std::path::Path;

/// Why a path was excluded — useful for debug logging and diagnostics.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BlacklistReason {
    /// Hardcoded exclusion (target, node_modules, .DS_Store).
    BuiltIn(&'static str),
    /// Matched a user-configured glob pattern.
    GlobPattern(String),
    /// FUSE stub file (.tc, .tcf extension).
    StubExtension,
    /// Hidden directory when `sync_hidden_dirs` is false.
    HiddenDir,
    /// .git directory when `sync_git_dirs` is false.
    GitDir,
    /// VFS internal directory marker (.tcfs_dir).
    VfsMarker,
}

impl std::fmt::Display for BlacklistReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BlacklistReason::BuiltIn(name) => write!(f, "built-in: {name}"),
            BlacklistReason::GlobPattern(pat) => write!(f, "glob: {pat}"),
            BlacklistReason::StubExtension => write!(f, "stub extension"),
            BlacklistReason::HiddenDir => write!(f, "hidden directory"),
            BlacklistReason::GitDir => write!(f, ".git directory"),
            BlacklistReason::VfsMarker => write!(f, "VFS marker"),
        }
    }
}

/// Built-in directory names that are always excluded.
const BUILTIN_DIRS: &[&str] = &["target", "node_modules"];

/// Built-in file names that are always excluded.
const BUILTIN_FILES: &[&str] = &[".DS_Store"];

/// VFS internal marker filename.
const VFS_MARKER: &str = ".tcfs_dir";

/// Stub file extensions generated by the FUSE layer.
const STUB_EXTENSIONS: &[&str] = &["tc", "tcf"];

/// Centralized exclusion filter for the sync pipeline.
///
/// Constructed once at startup from config, then passed to watcher, engine,
/// and VFS layers. All exclusion decisions flow through `check()`.
#[derive(Debug, Clone)]
pub struct Blacklist {
    globs: Vec<glob::Pattern>,
    sync_hidden_dirs: bool,
    sync_git_dirs: bool,
    git_sync_mode: String,
}

impl Default for Blacklist {
    fn default() -> Self {
        Self {
            globs: Vec::new(),
            sync_hidden_dirs: false,
            sync_git_dirs: false,
            git_sync_mode: "bundle".into(),
        }
    }
}

impl Blacklist {
    /// Construct from a `SyncConfig` (bridges existing config system).
    pub fn from_sync_config(cfg: &tcfs_core::config::SyncConfig) -> Self {
        let globs = cfg
            .exclude_patterns
            .iter()
            .filter_map(|p| glob::Pattern::new(p).ok())
            .collect();
        Self {
            globs,
            sync_hidden_dirs: cfg.sync_hidden_dirs,
            sync_git_dirs: cfg.sync_git_dirs,
            git_sync_mode: cfg.git_sync_mode.clone(),
        }
    }

    /// Construct from individual settings.
    pub fn new(
        exclude_patterns: &[String],
        sync_hidden_dirs: bool,
        sync_git_dirs: bool,
        git_sync_mode: &str,
    ) -> Self {
        let globs = exclude_patterns
            .iter()
            .filter_map(|p| glob::Pattern::new(p).ok())
            .collect();
        Self {
            globs,
            sync_hidden_dirs,
            sync_git_dirs,
            git_sync_mode: git_sync_mode.into(),
        }
    }

    /// The configured git sync mode ("bundle" or "raw").
    pub fn git_sync_mode(&self) -> &str {
        &self.git_sync_mode
    }

    /// Whether .git directories are allowed through the blacklist.
    pub fn allows_git_dirs(&self) -> bool {
        self.sync_git_dirs
    }

    /// Check a single filename/component. Returns first matching reason or None.
    ///
    /// This is the fast path for the watcher, which only has a name and no full path.
    pub fn check_name(&self, name: &str, is_dir: bool) -> Option<BlacklistReason> {
        // Built-in directory exclusions
        if is_dir && BUILTIN_DIRS.iter().any(|&b| b == name) {
            return Some(BlacklistReason::BuiltIn(
                BUILTIN_DIRS.iter().find(|&&b| b == name).unwrap(),
            ));
        }

        // Built-in file exclusions
        if BUILTIN_FILES.iter().any(|&b| b == name) {
            return Some(BlacklistReason::BuiltIn(
                BUILTIN_FILES.iter().find(|&&b| b == name).unwrap(),
            ));
        }

        // VFS internal marker
        if name == VFS_MARKER {
            return Some(BlacklistReason::VfsMarker);
        }

        // Stub extensions (.tc, .tcf)
        if let Some(ext) = Path::new(name).extension().and_then(|e| e.to_str()) {
            if STUB_EXTENSIONS.contains(&ext) {
                return Some(BlacklistReason::StubExtension);
            }
        }

        // User glob patterns
        for pat in &self.globs {
            if pat.matches(name) {
                return Some(BlacklistReason::GlobPattern(pat.as_str().into()));
            }
        }

        // .git directory — check before hidden dir rule
        if is_dir && name == ".git" {
            if !self.sync_git_dirs {
                return Some(BlacklistReason::GitDir);
            }
            // If sync_git_dirs is true, .git is explicitly allowed (skip hidden check)
            return None;
        }

        // Hidden directories (dot-prefixed, excluding .git handled above)
        if is_dir && name.starts_with('.') && !self.sync_hidden_dirs {
            return Some(BlacklistReason::HiddenDir);
        }

        None
    }

    /// Check a full path against the blacklist. Returns first matching reason or None.
    ///
    /// Checks the final component name against `check_name()`. For the watcher's
    /// component-walk behavior, use `check_path_components()` instead.
    pub fn check(&self, path: &Path, is_dir: bool) -> Option<BlacklistReason> {
        if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
            self.check_name(name, is_dir)
        } else {
            None
        }
    }

    /// Whether hidden directories are allowed through the blacklist.
    pub fn allows_hidden_dirs(&self) -> bool {
        self.sync_hidden_dirs
    }

    /// Get the raw glob pattern strings (for bridging to CollectConfig).
    pub fn glob_patterns(&self) -> Vec<String> {
        self.globs.iter().map(|p| p.as_str().to_string()).collect()
    }

    /// Check every component of a path (for watcher-style full-path filtering).
    ///
    /// Returns the reason for the first matching component, or None if all pass.
    pub fn check_path_components(&self, path: &Path) -> Option<BlacklistReason> {
        for component in path.components() {
            if let std::path::Component::Normal(name) = component {
                if let Some(name_str) = name.to_str() {
                    // Treat intermediate components as directories
                    if let Some(reason) = self.check_name(name_str, true) {
                        return Some(reason);
                    }
                }
            }
        }
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn default_blacklist() -> Blacklist {
        Blacklist::default()
    }

    fn blacklist_with_globs(patterns: &[&str]) -> Blacklist {
        let pats: Vec<String> = patterns.iter().map(|s| s.to_string()).collect();
        Blacklist::new(&pats, false, false, "bundle")
    }

    #[test]
    fn test_builtin_dir_exclusions() {
        let bl = default_blacklist();
        assert_eq!(
            bl.check_name("target", true),
            Some(BlacklistReason::BuiltIn("target"))
        );
        assert_eq!(
            bl.check_name("node_modules", true),
            Some(BlacklistReason::BuiltIn("node_modules"))
        );
        // Not excluded as files
        assert_eq!(bl.check_name("target", false), None);
    }

    #[test]
    fn test_builtin_file_exclusions() {
        let bl = default_blacklist();
        assert_eq!(
            bl.check_name(".DS_Store", false),
            Some(BlacklistReason::BuiltIn(".DS_Store"))
        );
    }

    #[test]
    fn test_vfs_marker() {
        let bl = default_blacklist();
        assert_eq!(
            bl.check_name(".tcfs_dir", false),
            Some(BlacklistReason::VfsMarker)
        );
        assert_eq!(
            bl.check_name(".tcfs_dir", true),
            Some(BlacklistReason::VfsMarker)
        );
    }

    #[test]
    fn test_stub_extensions() {
        let bl = default_blacklist();
        assert_eq!(
            bl.check_name("file.tc", false),
            Some(BlacklistReason::StubExtension)
        );
        assert_eq!(
            bl.check_name("folder.tcf", false),
            Some(BlacklistReason::StubExtension)
        );
        // Normal extensions pass
        assert_eq!(bl.check_name("file.txt", false), None);
    }

    #[test]
    fn test_glob_patterns() {
        let bl = blacklist_with_globs(&["*.swp", "*.tmp", "__pycache__"]);
        assert_eq!(
            bl.check_name("edit.swp", false),
            Some(BlacklistReason::GlobPattern("*.swp".into()))
        );
        assert_eq!(
            bl.check_name("data.tmp", false),
            Some(BlacklistReason::GlobPattern("*.tmp".into()))
        );
        assert_eq!(
            bl.check_name("__pycache__", true),
            Some(BlacklistReason::GlobPattern("__pycache__".into()))
        );
        assert_eq!(bl.check_name("main.rs", false), None);
    }

    #[test]
    fn test_git_dir_policy() {
        // Default: .git excluded
        let bl = Blacklist::default();
        assert_eq!(bl.check_name(".git", true), Some(BlacklistReason::GitDir));

        // With sync_git_dirs: .git allowed through
        let bl = Blacklist::new(&[], false, true, "bundle");
        assert_eq!(bl.check_name(".git", true), None);
    }

    #[test]
    fn test_hidden_dir_policy() {
        // Default: hidden dirs excluded
        let bl = Blacklist::default();
        assert_eq!(
            bl.check_name(".config", true),
            Some(BlacklistReason::HiddenDir)
        );
        assert_eq!(
            bl.check_name(".env", true),
            Some(BlacklistReason::HiddenDir)
        );

        // With sync_hidden_dirs: allowed
        let bl = Blacklist::new(&[], true, false, "bundle");
        assert_eq!(bl.check_name(".config", true), None);
    }

    #[test]
    fn test_allowed_paths() {
        let bl = default_blacklist();
        assert_eq!(bl.check_name("src", true), None);
        assert_eq!(bl.check_name("main.rs", false), None);
        assert_eq!(bl.check_name("Cargo.toml", false), None);
        assert_eq!(bl.check_name("README.md", false), None);
    }

    #[test]
    fn test_check_full_path() {
        let bl = default_blacklist();
        let path = Path::new("/home/user/project/target");
        assert!(bl.check(path, true).is_some());

        let path = Path::new("/home/user/project/src/main.rs");
        assert!(bl.check(path, false).is_none());
    }

    #[test]
    fn test_check_path_components() {
        let bl = default_blacklist();
        let path = Path::new("project/node_modules/package/index.js");
        assert_eq!(
            bl.check_path_components(path),
            Some(BlacklistReason::BuiltIn("node_modules"))
        );

        let path = Path::new("project/src/main.rs");
        assert_eq!(bl.check_path_components(path), None);
    }
}
