//! Centralized exclusion logic for the sync pipeline.
//!
//! Consolidates six scattered filtering sites (watcher, engine, VFS, git safety)
//! into a single `Blacklist` type with a unified `check()` method.

use std::path::Path;
use tracing::debug;

/// Why a path was excluded — useful for debug logging and diagnostics.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BlacklistReason {
    /// Hardcoded exclusion (target, node_modules, .DS_Store).
    BuiltIn(&'static str),
    /// Fail-closed security exclusion: secret store, credential file, or live
    /// database. Always denied regardless of user config (TIN-1737 / Gate G0).
    Security(&'static str),
    /// Matched a user-configured glob pattern.
    GlobPattern(String),
    /// Physical sync-root stub file (.tc, .tcf extension).
    StubExtension,
    /// Hidden directory when `sync_hidden_dirs` is false.
    HiddenDir,
    /// .git directory when `sync_git_dirs` is false.
    GitDir,
    /// Fail-closed worktree fence: a non-directory named `.git` is a linked
    /// worktree's (or submodule's) gitfile pointer (`gitdir: <path>`). It
    /// dangles on any other host, and a roamed deletion of the admin area it
    /// points at would destroy the origin host's live worktree. Always denied
    /// regardless of `sync_git_dirs` / `git_sync_mode` (G5 / TIN-1620).
    GitFilePointer,
    /// Fail-closed worktree fence: any path containing a `.git/worktrees/`
    /// segment — the per-worktree admin area (`HEAD`, `index`, `gitdir` with
    /// absolute host paths). Always denied, even under `sync_git_dirs=true`
    /// with `git_sync_mode="raw"` (G5 / TIN-1620).
    GitWorktreesAdmin,
    /// Fail-closed lockfile fence: a transient git lockfile under a `.git/`
    /// directory — the TCFS cooperative `.git/tcfs.lock`, or git's own
    /// `index.lock` / `HEAD.lock` / `<ref>.lock` / `packed-refs.lock`. Roaming
    /// a leaked lock would make it join `.git` conflict groups and, probed
    /// against a foreign PID table, could wedge peers into permanent
    /// proceed-without-lock. Always denied, even under `sync_git_dirs=true`
    /// with `git_sync_mode="raw"` (M-3 / PR #513). `Cargo.lock` / `flake.lock`
    /// live OUTSIDE `.git`, so they are unaffected.
    GitLockFile,
    /// Fail-closed undo-bundle fence: any path containing a `.git/tcfs-undo/`
    /// segment — the legacy in-tree location of the keep-both undo bundle. The
    /// bundle now lives under the machine-local state dir (see
    /// `conflict_git::write_undo_bundle`), but a pre-existing in-tree bundle
    /// (full-history `git bundle --all`, fresh uuid, never GC'd) must never
    /// roam. Always denied, even under `sync_git_dirs=true` /
    /// `git_sync_mode="raw"` (BLOCKING 2 / #529).
    GitTcfsUndo,
    /// VFS internal directory marker (.tcfs_dir).
    VfsMarker,
}

impl std::fmt::Display for BlacklistReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BlacklistReason::BuiltIn(name) => write!(f, "built-in: {name}"),
            BlacklistReason::Security(kind) => write!(f, "security: {kind}"),
            BlacklistReason::GlobPattern(pat) => write!(f, "glob: {pat}"),
            BlacklistReason::StubExtension => write!(f, "stub extension"),
            BlacklistReason::HiddenDir => write!(f, "hidden directory"),
            BlacklistReason::GitDir => write!(f, ".git directory"),
            BlacklistReason::GitFilePointer => write!(f, "gitfile pointer (linked worktree)"),
            BlacklistReason::GitWorktreesAdmin => write!(f, ".git/worktrees admin area"),
            BlacklistReason::GitLockFile => write!(f, "git lockfile"),
            BlacklistReason::GitTcfsUndo => write!(f, ".git/tcfs-undo bundle"),
            BlacklistReason::VfsMarker => write!(f, "VFS marker"),
        }
    }
}

/// Built-in directory names that are always excluded.
const BUILTIN_DIRS: &[&str] = &["target", "node_modules"];

/// Built-in file names that are always excluded.
const BUILTIN_FILES: &[&str] = &[".DS_Store"];

/// VFS internal marker filename.
const VFS_MARKER: &str = ".tcfs_dir";

/// Stub file extensions generated by the FUSE layer.
const STUB_EXTENSIONS: &[&str] = &["tc", "tcf"];

/// Directory component names that are ALWAYS excluded for security — secret and
/// credential stores that must never leave the device. Fail-closed: denied
/// regardless of user config, and matched on any path component so a file
/// nested under one of these (e.g. `~/.ssh/id_ed25519`) is also excluded.
/// (TIN-1737 / Gate G0.)
const SECURITY_DIRS: &[&str] = &[".ssh", ".gnupg", "sops-nix"];

/// Exact file names that are ALWAYS excluded for security (credential files).
const SECURITY_FILES: &[&str] = &[".credentials.json", "auth.json", ".netrc", ".pgpass"];

/// Live database file suffixes that are ALWAYS excluded. Syncing an open-WAL
/// SQLite/DB file is a corruption hazard, so these are denied until a
/// snapshot-safe story exists (tracked under the agent-dir beachhead).
const SECURITY_DB_SUFFIXES: &[&str] = &[
    ".sqlite",
    ".sqlite3",
    ".sqlite-wal",
    ".sqlite-shm",
    ".db",
    ".db-wal",
    ".db-shm",
];

/// Classify a file name against the fail-closed security deny-set.
///
/// Returns a stable static label when the name is a secret/credential/live-DB
/// file. Checked before user glob patterns so it cannot be overridden.
fn security_file_reason(name: &str) -> Option<&'static str> {
    for &f in SECURITY_FILES {
        if name == f {
            return Some(f);
        }
    }
    // dotenv: `.env`, `.env.local`, `service.env`
    if name == ".env" || name.starts_with(".env.") || name.ends_with(".env") {
        return Some("dotenv");
    }
    for &suf in SECURITY_DB_SUFFIXES {
        if name.ends_with(suf) {
            return Some("live-db");
        }
    }
    None
}

/// True when `path` contains a `.git/worktrees/` segment — the per-worktree
/// admin area git maintains for linked worktrees (`HEAD`, `index`, `gitdir`
/// files that embed absolute host paths). Roamed raw these dangle, and a
/// roamed `git worktree prune` deletion would sync back and destroy the
/// origin host's live worktree. Fail-closed: fenced regardless of config
/// (G5 / TIN-1620).
fn has_git_worktrees_segment(path: &Path) -> bool {
    let mut prev_was_dot_git = false;
    for component in path.components() {
        match component {
            std::path::Component::Normal(name) => {
                if prev_was_dot_git && name == "worktrees" {
                    return true;
                }
                prev_was_dot_git = name == ".git";
            }
            _ => prev_was_dot_git = false,
        }
    }
    false
}

/// True when `path` contains a `.git/tcfs-undo/` segment — the legacy in-tree
/// location of the keep-both undo bundle (a full-history `git bundle --all`
/// with a fresh uuid, never GC'd). The bundle now lives under the machine-local
/// state dir, but a pre-existing in-tree bundle must never roam as an ordinary
/// `.git/**` file. Fail-closed regardless of config (BLOCKING 2 / #529).
fn has_git_tcfs_undo_segment(path: &Path) -> bool {
    let mut prev_was_dot_git = false;
    for component in path.components() {
        match component {
            std::path::Component::Normal(name) => {
                if prev_was_dot_git && name == "tcfs-undo" {
                    return true;
                }
                prev_was_dot_git = name == ".git";
            }
            _ => prev_was_dot_git = false,
        }
    }
    false
}

/// True when `path` is a transient git lockfile that must never roam: the TCFS
/// cooperative `.git/tcfs.lock`, or any git lockfile (`index.lock`,
/// `HEAD.lock`, `<ref>.lock`, `packed-refs.lock`, ...) — i.e. a `*.lock` file
/// anywhere INSIDE a `.git/` directory. A leaked/roamed lock joins `.git`
/// conflict groups and, probed against a foreign PID table, can wedge peers
/// into permanent proceed-without-lock. Scoped to `.git` so `Cargo.lock` /
/// `flake.lock` (which live outside `.git`) still roam. Fail-closed regardless
/// of config (M-3 / PR #513).
fn is_git_lockfile_path(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
        return false;
    };
    if !name.ends_with(".lock") {
        return false;
    }
    // The lockfile must be strictly inside a `.git` directory: some component
    // before the final one is named `.git`.
    path.components()
        .any(|c| matches!(c, std::path::Component::Normal(n) if n == ".git"))
}

/// Centralized exclusion filter for the sync pipeline.
///
/// Constructed once at startup from config, then passed to watcher, engine,
/// and VFS layers. All exclusion decisions flow through `check()`.
#[derive(Debug, Clone)]
pub struct Blacklist {
    globs: Vec<glob::Pattern>,
    sync_hidden_dirs: bool,
    sync_git_dirs: bool,
    git_sync_mode: String,
}

impl Default for Blacklist {
    fn default() -> Self {
        Self {
            globs: Vec::new(),
            sync_hidden_dirs: false,
            sync_git_dirs: false,
            git_sync_mode: "bundle".into(),
        }
    }
}

impl Blacklist {
    /// Construct from a `SyncConfig` (bridges existing config system).
    pub fn from_sync_config(cfg: &tcfs_core::config::SyncConfig) -> Self {
        let globs = cfg
            .exclude_patterns
            .iter()
            .filter_map(|p| glob::Pattern::new(p).ok())
            .collect();
        Self {
            globs,
            sync_hidden_dirs: cfg.sync_hidden_dirs,
            sync_git_dirs: cfg.sync_git_dirs,
            git_sync_mode: cfg.git_sync_mode.clone(),
        }
    }

    /// Construct from individual settings.
    pub fn new(
        exclude_patterns: &[String],
        sync_hidden_dirs: bool,
        sync_git_dirs: bool,
        git_sync_mode: &str,
    ) -> Self {
        let globs = exclude_patterns
            .iter()
            .filter_map(|p| glob::Pattern::new(p).ok())
            .collect();
        Self {
            globs,
            sync_hidden_dirs,
            sync_git_dirs,
            git_sync_mode: git_sync_mode.into(),
        }
    }

    /// The configured git sync mode ("bundle" or "raw").
    pub fn git_sync_mode(&self) -> &str {
        &self.git_sync_mode
    }

    /// Whether .git directories are allowed through the blacklist.
    pub fn allows_git_dirs(&self) -> bool {
        self.sync_git_dirs
    }

    /// Check a single filename/component. Returns first matching reason or None.
    ///
    /// This is the fast path for the watcher, which only has a name and no full path.
    pub fn check_name(&self, name: &str, is_dir: bool) -> Option<BlacklistReason> {
        // Security deny-set — fail-closed, highest priority. Cannot be
        // overridden by config and is checked before the hidden-dir rule, which
        // is disabled when `sync_hidden_dirs` is true (e.g. agent dotdirs).
        // (TIN-1737 / Gate G0.)
        for &d in SECURITY_DIRS {
            if name == d {
                return Some(BlacklistReason::Security(d));
            }
        }
        if let Some(label) = security_file_reason(name) {
            return Some(BlacklistReason::Security(label));
        }

        // Built-in directory exclusions
        if is_dir && BUILTIN_DIRS.contains(&name) {
            return Some(BlacklistReason::BuiltIn(
                BUILTIN_DIRS.iter().find(|&&b| b == name).unwrap(),
            ));
        }

        // Built-in file exclusions
        if BUILTIN_FILES.contains(&name) {
            return Some(BlacklistReason::BuiltIn(
                BUILTIN_FILES.iter().find(|&&b| b == name).unwrap(),
            ));
        }

        // VFS internal marker
        if name == VFS_MARKER {
            return Some(BlacklistReason::VfsMarker);
        }

        // Stub extensions (.tc, .tcf)
        if let Some(ext) = Path::new(name).extension().and_then(|e| e.to_str()) {
            if STUB_EXTENSIONS.contains(&ext) {
                return Some(BlacklistReason::StubExtension);
            }
        }

        // User glob patterns
        for pat in &self.globs {
            if pat.matches(name) {
                return Some(BlacklistReason::GlobPattern(pat.as_str().into()));
            }
        }

        // .git — worktree fence first, then the config-gated dir rule (before
        // the hidden dir rule).
        if name == ".git" {
            // Fail-closed worktree fence: a non-directory named `.git` is a
            // linked worktree's (or submodule's) gitfile pointer. Never roam
            // it, regardless of `sync_git_dirs` / `git_sync_mode`
            // (G5 / TIN-1620).
            if !is_dir {
                debug!("fencing gitfile pointer: non-directory .git never roams");
                return Some(BlacklistReason::GitFilePointer);
            }
            if !self.sync_git_dirs {
                return Some(BlacklistReason::GitDir);
            }
            // If sync_git_dirs is true, .git is explicitly allowed (skip hidden check)
            return None;
        }

        // Hidden directories (dot-prefixed, excluding .git handled above)
        if is_dir && name.starts_with('.') && !self.sync_hidden_dirs {
            return Some(BlacklistReason::HiddenDir);
        }

        None
    }

    /// Check a full path against the blacklist. Returns first matching reason or None.
    ///
    /// Applies the fail-closed `.git/worktrees/` fence across the whole path,
    /// then checks the final component name against `check_name()`. For the
    /// watcher's component-walk behavior, use `check_path_components()` instead.
    pub fn check(&self, path: &Path, is_dir: bool) -> Option<BlacklistReason> {
        if has_git_worktrees_segment(path) {
            debug!(
                path = %path.display(),
                "fencing .git/worktrees admin area: never roams"
            );
            return Some(BlacklistReason::GitWorktreesAdmin);
        }
        if is_git_lockfile_path(path) {
            debug!(path = %path.display(), "fencing git lockfile: never roams");
            return Some(BlacklistReason::GitLockFile);
        }
        if has_git_tcfs_undo_segment(path) {
            debug!(path = %path.display(), "fencing .git/tcfs-undo bundle: never roams");
            return Some(BlacklistReason::GitTcfsUndo);
        }
        if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
            self.check_name(name, is_dir)
        } else {
            None
        }
    }

    /// Whether hidden directories are allowed through the blacklist.
    pub fn allows_hidden_dirs(&self) -> bool {
        self.sync_hidden_dirs
    }

    /// Get the raw glob pattern strings (for bridging to CollectConfig).
    pub fn glob_patterns(&self) -> Vec<String> {
        self.globs.iter().map(|p| p.as_str().to_string()).collect()
    }

    /// Check every component of a path (for watcher-style full-path filtering).
    ///
    /// Returns the reason for the first matching component, or None if all pass.
    /// Also applies the fail-closed `.git/worktrees/` fence across the whole
    /// path (G5 / TIN-1620).
    pub fn check_path_components(&self, path: &Path) -> Option<BlacklistReason> {
        if has_git_worktrees_segment(path) {
            debug!(
                path = %path.display(),
                "fencing .git/worktrees admin area: never roams"
            );
            return Some(BlacklistReason::GitWorktreesAdmin);
        }
        if is_git_lockfile_path(path) {
            debug!(path = %path.display(), "fencing git lockfile: never roams");
            return Some(BlacklistReason::GitLockFile);
        }
        if has_git_tcfs_undo_segment(path) {
            debug!(path = %path.display(), "fencing .git/tcfs-undo bundle: never roams");
            return Some(BlacklistReason::GitTcfsUndo);
        }
        for component in path.components() {
            if let std::path::Component::Normal(name) = component {
                if let Some(name_str) = name.to_str() {
                    // Treat intermediate components as directories
                    if let Some(reason) = self.check_name(name_str, true) {
                        return Some(reason);
                    }
                }
            }
        }
        None
    }

    /// Check only the fail-closed deny-sets across every path component: the
    /// security deny-set plus the config-independent `.git/worktrees/` fence.
    ///
    /// This is for cases where a caller intentionally starts from a hidden root
    /// such as `~/.claude/projects`, but must still refuse credential stores,
    /// dotenv files, and live databases anywhere under that root.
    pub fn check_security_path_components(&self, path: &Path) -> Option<BlacklistReason> {
        if has_git_worktrees_segment(path) {
            debug!(
                path = %path.display(),
                "fencing .git/worktrees admin area: never roams"
            );
            return Some(BlacklistReason::GitWorktreesAdmin);
        }
        for component in path.components() {
            if let std::path::Component::Normal(name) = component {
                if let Some(name_str) = name.to_str() {
                    for &dir in SECURITY_DIRS {
                        if name_str == dir {
                            return Some(BlacklistReason::Security(dir));
                        }
                    }
                    if let Some(label) = security_file_reason(name_str) {
                        return Some(BlacklistReason::Security(label));
                    }
                }
            }
        }
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn default_blacklist() -> Blacklist {
        Blacklist::default()
    }

    fn blacklist_with_globs(patterns: &[&str]) -> Blacklist {
        let pats: Vec<String> = patterns.iter().map(|s| s.to_string()).collect();
        Blacklist::new(&pats, false, false, "bundle")
    }

    #[test]
    fn test_builtin_dir_exclusions() {
        let bl = default_blacklist();
        assert_eq!(
            bl.check_name("target", true),
            Some(BlacklistReason::BuiltIn("target"))
        );
        assert_eq!(
            bl.check_name("node_modules", true),
            Some(BlacklistReason::BuiltIn("node_modules"))
        );
        // Not excluded as files
        assert_eq!(bl.check_name("target", false), None);
    }

    #[test]
    fn test_builtin_file_exclusions() {
        let bl = default_blacklist();
        assert_eq!(
            bl.check_name(".DS_Store", false),
            Some(BlacklistReason::BuiltIn(".DS_Store"))
        );
    }

    #[test]
    fn test_vfs_marker() {
        let bl = default_blacklist();
        assert_eq!(
            bl.check_name(".tcfs_dir", false),
            Some(BlacklistReason::VfsMarker)
        );
        assert_eq!(
            bl.check_name(".tcfs_dir", true),
            Some(BlacklistReason::VfsMarker)
        );
    }

    #[test]
    fn test_stub_extensions() {
        let bl = default_blacklist();
        assert_eq!(
            bl.check_name("file.tc", false),
            Some(BlacklistReason::StubExtension)
        );
        assert_eq!(
            bl.check_name("folder.tcf", false),
            Some(BlacklistReason::StubExtension)
        );
        // Normal extensions pass
        assert_eq!(bl.check_name("file.txt", false), None);
    }

    #[test]
    fn test_glob_patterns() {
        let bl = blacklist_with_globs(&["*.swp", "*.tmp", "__pycache__"]);
        assert_eq!(
            bl.check_name("edit.swp", false),
            Some(BlacklistReason::GlobPattern("*.swp".into()))
        );
        assert_eq!(
            bl.check_name("data.tmp", false),
            Some(BlacklistReason::GlobPattern("*.tmp".into()))
        );
        assert_eq!(
            bl.check_name("__pycache__", true),
            Some(BlacklistReason::GlobPattern("__pycache__".into()))
        );
        assert_eq!(bl.check_name("main.rs", false), None);
    }

    #[test]
    fn test_git_dir_policy() {
        // Default: .git excluded
        let bl = Blacklist::default();
        assert_eq!(bl.check_name(".git", true), Some(BlacklistReason::GitDir));

        // With sync_git_dirs: .git allowed through
        let bl = Blacklist::new(&[], false, true, "bundle");
        assert_eq!(bl.check_name(".git", true), None);
    }

    #[test]
    fn test_hidden_dir_policy() {
        // Default: hidden dirs excluded
        let bl = Blacklist::default();
        assert_eq!(
            bl.check_name(".config", true),
            Some(BlacklistReason::HiddenDir)
        );
        // Note: `.env` is now caught by the security deny-set, not HiddenDir;
        // use a non-secret hidden dir to exercise the hidden-dir rule.
        assert_eq!(
            bl.check_name(".cache", true),
            Some(BlacklistReason::HiddenDir)
        );

        // With sync_hidden_dirs: allowed
        let bl = Blacklist::new(&[], true, false, "bundle");
        assert_eq!(bl.check_name(".config", true), None);
    }

    #[test]
    fn test_allowed_paths() {
        let bl = default_blacklist();
        assert_eq!(bl.check_name("src", true), None);
        assert_eq!(bl.check_name("main.rs", false), None);
        assert_eq!(bl.check_name("Cargo.toml", false), None);
        assert_eq!(bl.check_name("README.md", false), None);
    }

    #[test]
    fn test_check_full_path() {
        let bl = default_blacklist();
        let path = Path::new("/home/user/project/target");
        assert!(bl.check(path, true).is_some());

        let path = Path::new("/home/user/project/src/main.rs");
        assert!(bl.check(path, false).is_none());
    }

    #[test]
    fn test_check_path_components() {
        let bl = default_blacklist();
        let path = Path::new("project/node_modules/package/index.js");
        assert_eq!(
            bl.check_path_components(path),
            Some(BlacklistReason::BuiltIn("node_modules"))
        );

        let path = Path::new("project/src/main.rs");
        assert_eq!(bl.check_path_components(path), None);
    }

    // --- TIN-1737 / Gate G0: fail-closed security deny-set ---

    #[test]
    fn test_security_dirs_denied() {
        let bl = default_blacklist();
        for dir in [".ssh", ".gnupg", "sops-nix"] {
            assert!(
                matches!(bl.check_name(dir, true), Some(BlacklistReason::Security(_))),
                "expected {dir} to be security-denied"
            );
        }
    }

    #[test]
    fn test_security_credential_files_denied() {
        let bl = default_blacklist();
        for file in [".credentials.json", "auth.json", ".netrc", ".pgpass"] {
            assert!(
                matches!(
                    bl.check_name(file, false),
                    Some(BlacklistReason::Security(_))
                ),
                "expected {file} to be security-denied"
            );
        }
    }

    #[test]
    fn test_security_dotenv_and_db_denied() {
        let bl = default_blacklist();
        for name in [
            ".env",
            ".env.local",
            "service.env",
            "logs_2.sqlite",
            "logs_2.sqlite-wal",
            "logs_2.sqlite-shm",
            "opencode.db",
            "state.db-wal",
        ] {
            assert!(
                matches!(
                    bl.check_name(name, false),
                    Some(BlacklistReason::Security(_))
                ),
                "expected {name} to be security-denied"
            );
        }
    }

    #[test]
    fn test_security_is_fail_closed_with_hidden_dirs_allowed() {
        // The agent-dir beachhead needs sync_hidden_dirs=true, which removes the
        // HiddenDir guard. The security deny-set must still hold.
        let bl = Blacklist::new(&[], true, true, "raw");
        assert!(matches!(
            bl.check_name(".ssh", true),
            Some(BlacklistReason::Security(_))
        ));
        assert!(matches!(
            bl.check_name(".credentials.json", false),
            Some(BlacklistReason::Security(_))
        ));
    }

    #[test]
    fn test_security_denied_nested_in_path() {
        let bl = Blacklist::new(&[], true, true, "raw");
        // A secret nested under a secret dir is caught via component walk.
        for path in [
            "home/jess/.ssh/id_ed25519",
            "home/jess/.config/sops-nix/secrets/database",
            "home/jess/.codex/logs_2.sqlite",
            "repo/.env",
        ] {
            assert!(
                matches!(
                    bl.check_path_components(Path::new(path)),
                    Some(BlacklistReason::Security(_))
                ),
                "expected {path} to be security-denied via component walk"
            );
        }
    }

    #[test]
    fn test_security_only_component_walk_allows_hidden_agent_root() {
        let bl = Blacklist::new(&[], false, true, "raw");
        assert_eq!(
            bl.check_security_path_components(Path::new(
                "home/jess/.claude/projects/session.jsonl"
            )),
            None
        );
        assert!(matches!(
            bl.check_security_path_components(Path::new("home/jess/.claude/.credentials.json")),
            Some(BlacklistReason::Security(".credentials.json"))
        ));
        assert!(matches!(
            bl.check_security_path_components(Path::new("home/jess/.config/sops-nix/secrets/key")),
            Some(BlacklistReason::Security("sops-nix"))
        ));
    }

    // --- G5 / TIN-1620: linked-worktree fence (gitfile pointers + .git/worktrees) ---

    #[test]
    fn test_worktree_gitfile_pointer_denied_at_repo_root() {
        // (a) A non-directory `.git` — a linked worktree's gitfile pointer —
        // is fenced even under the most permissive config.
        let bl = Blacklist::new(&[], true, true, "raw");
        assert_eq!(
            bl.check_name(".git", false),
            Some(BlacklistReason::GitFilePointer)
        );
        assert_eq!(
            bl.check(Path::new("wt-linked/.git"), false),
            Some(BlacklistReason::GitFilePointer)
        );
        // Default (git sync off) is denied too — fail closed either way.
        let bl = Blacklist::default();
        assert_eq!(
            bl.check_name(".git", false),
            Some(BlacklistReason::GitFilePointer)
        );
    }

    #[test]
    fn test_worktrees_admin_area_denied_under_raw() {
        // (b) `.git/worktrees/**` never roams, even with sync_git_dirs=true
        // and git_sync_mode="raw".
        let bl = Blacklist::new(&[], true, true, "raw");
        for p in [
            "repo/.git/worktrees",
            "repo/.git/worktrees/wt-fence/gitdir",
            "repo/.git/worktrees/wt-fence/HEAD",
            "repo/.git/worktrees/wt-fence/index",
        ] {
            assert_eq!(
                bl.check(Path::new(p), false),
                Some(BlacklistReason::GitWorktreesAdmin),
                "expected {p} to be fenced via check()"
            );
            assert_eq!(
                bl.check_path_components(Path::new(p)),
                Some(BlacklistReason::GitWorktreesAdmin),
                "expected {p} to be fenced via component walk"
            );
        }
        // The security-only walk fences it too (config-independent).
        assert_eq!(
            bl.check_security_path_components(Path::new("repo/.git/worktrees/wt/HEAD")),
            Some(BlacklistReason::GitWorktreesAdmin)
        );
    }

    #[test]
    fn test_raw_git_dir_internals_still_roam() {
        // (c) Regular .git internals are unaffected — the proven raw forward
        // roam must not regress.
        let bl = Blacklist::new(&[], true, true, "raw");
        assert_eq!(bl.check_name(".git", true), None);
        for p in [
            "repo/.git/objects/ab/cdef0123456789",
            "repo/.git/refs/heads/main",
            "repo/.git/HEAD",
            "repo/.git/config",
        ] {
            assert_eq!(bl.check(Path::new(p), false), None, "{p} should pass");
            assert_eq!(
                bl.check_path_components(Path::new(p)),
                None,
                "{p} should pass component walk"
            );
        }
        // A directory named `worktrees` NOT under `.git` is a normal dir.
        assert_eq!(bl.check(Path::new("repo/worktrees/notes.md"), false), None);
    }

    // --- M-3 / PR #513: transient git lockfiles never roam ---
    #[test]
    fn test_git_lockfiles_denied_even_under_raw() {
        // sync_git_dirs=true + git_sync_mode="raw" lets `.git/**` through, but
        // transient lockfiles (tcfs.lock, index.lock, <ref>.lock, ...) must be
        // fenced fail-closed — both via check() and the component walk.
        let bl = Blacklist::new(&[], true, true, "raw");
        for p in [
            "repo/.git/tcfs.lock",
            "repo/.git/index.lock",
            "repo/.git/HEAD.lock",
            "repo/.git/refs/heads/main.lock",
            "repo/.git/packed-refs.lock",
            "repo/vendor/dep/.git/index.lock",
        ] {
            assert_eq!(
                bl.check(Path::new(p), false),
                Some(BlacklistReason::GitLockFile),
                "{p} must be lockfile-fenced via check()"
            );
            assert_eq!(
                bl.check_path_components(Path::new(p)),
                Some(BlacklistReason::GitLockFile),
                "{p} must be lockfile-fenced via component walk"
            );
        }
        // A real ref file (not a lock) under raw still roams.
        assert_eq!(
            bl.check(Path::new("repo/.git/refs/heads/main"), false),
            None
        );
        // `Cargo.lock` / `flake.lock` live OUTSIDE `.git` and must still roam.
        assert_eq!(bl.check(Path::new("repo/Cargo.lock"), false), None);
        assert_eq!(bl.check(Path::new("repo/flake.lock"), false), None);
        assert_eq!(bl.check_name("Cargo.lock", false), None);
    }

    // --- BLOCKING 2 / #529: in-tree keep-both undo bundle never roams ---
    #[test]
    fn test_git_tcfs_undo_denied_even_under_raw() {
        // The undo bundle now lives under the state dir, but a pre-existing
        // in-tree `.git/tcfs-undo/**` bundle must be fenced fail-closed even
        // with sync_git_dirs=true + git_sync_mode="raw".
        let bl = Blacklist::new(&[], true, true, "raw");
        for p in [
            "repo/.git/tcfs-undo/keep-both-abc.bundle",
            "repo/vendor/dep/.git/tcfs-undo/keep-both-xyz.bundle",
        ] {
            assert_eq!(
                bl.check(Path::new(p), false),
                Some(BlacklistReason::GitTcfsUndo),
                "{p} must be undo-fenced via check()"
            );
            assert_eq!(
                bl.check_path_components(Path::new(p)),
                Some(BlacklistReason::GitTcfsUndo),
                "{p} must be undo-fenced via component walk"
            );
        }
        // A dir named `tcfs-undo` NOT under `.git` is a normal dir.
        assert_eq!(bl.check(Path::new("repo/tcfs-undo/notes.md"), false), None);
    }

    #[test]
    fn test_nested_gitfile_pointer_denied_fail_closed() {
        // (d) A non-directory named `.git` anywhere in the tree (submodule
        // pointer shape) is fenced — fail closed.
        let bl = Blacklist::new(&[], true, true, "raw");
        assert_eq!(
            bl.check(Path::new("repo/vendor/dep/.git"), false),
            Some(BlacklistReason::GitFilePointer)
        );
        // As a directory it follows the normal .git-dir policy instead.
        assert_eq!(bl.check(Path::new("repo/vendor/dep/.git"), true), None);
    }

    #[test]
    fn test_security_does_not_overblock_legit_files() {
        // Agent transcripts (.jsonl) and normal source must still pass even with
        // hidden dirs allowed.
        let bl = Blacklist::new(&[], true, false, "bundle");
        for name in [
            "session-abc.jsonl",
            "main.rs",
            "Cargo.toml",
            "notes.md",
            ".envrc",
            "config.json",
            "data.dbf",
        ] {
            assert_eq!(bl.check_name(name, false), None, "{name} should pass");
        }
        // A normal project subtree with a jsonl transcript passes end to end.
        assert_eq!(
            bl.check_path_components(Path::new(".claude/projects/proj/session.jsonl")),
            None
        );
    }
}
